openapi: 3.0.3
info:
  title: ALbion_Beacon Local API (Mock)
  version: 0.1.0
servers:
  - url: http://127.0.0.1:8787
paths:
  /v1/health:
    get:
      responses:
        '200': { description: OK }
  /v1/auth/gate:
    post:
      requestBody: { required: true }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthGate'
  /v1/heartbeat:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationHeartbeat'
      responses:
        '200': { description: OK }
  /v1/events/nearby:
    get:
      parameters:
        - name: hop
          in: query
          schema: { type: integer, maximum: 8, default: 8 }
      responses:
        '200': { description: OK }
components:
  schemas:
    LocationHeartbeat:
      type: object
      required: [nick, region, ts]
      properties:
        nick: { type: string }
        region: { type: string }
        pos:
          type: [object, 'null']
          properties:
            x: { type: number, minimum: 0, maximum: 1 }
            y: { type: number, minimum: 0, maximum: 1 }
          required: [x, y]
        party:
          type: [integer, 'null']
          minimum: 1
          maximum: 20
        ts: { type: integer }
    AuthGate:
      type: object
      required: [nick, gm]
      properties:
        nick: { type: string }
        gm: { type: boolean }
