name: CI
on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate contracts exist
        run: test -f contracts/openapi.yaml && test -f contracts/location.schema.json
      - name: Generate doc summary
        shell: bash
        run: |
          python3 - <<'PY'
from pathlib import Path
Path('docs/API_SUMMARY.md').write_text('# API Summary (auto)\n\n- Source: contracts/openapi.yaml\n')
PY
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/
